### ISSUE TITLE
Warn if Timer frequency is not met

### ISSUE THREAD

**Issue by tonynajjar** [ros2/rclpy#1126]
#### Feature description
How about adding a warning if the timer frequency is not met? That would be useful for the user to either decrease the frequency or optimize the callback.

#### Implementation considerations

In case the timer is implemented with a ReentrantCallback group, another instance of the callback would always fire; we should decide if we want to warn nevertheless if the first instance of the callback takes longer than expected to complete :thinking:

**Comment by fujitatomoya** [comment]
i think that would be helpful.

> How about adding a warning if the timer frequency is not met?

required accuracy is really dependent on user application. for doing this, i think we do need to ask application about acceptable jitter or something like that to the timer?

my concern is there would be many warning messages. i think there are many possibilities that can cause this warning, executor becomes busy, system is busy and so on. to avoid having many warnings, probably it can print just once when the requirement does not match. and then we are not sure how often it happens, which is really good information if we want to tune the timer frequency. we can have time window for warning message, but it gives more complexity for the timer?

sorry, i just left my note above, i really do not have good idea. i would like to ask for comments on this.

**Comment by apockill** [comment]
I'm all for more visibility when it comes to logging, but I wouldn't want to add more complexity or compute to the system. 

What if before a timer callback gets called, a check is performed to see if the (time - last_time_run) > intended_delay, and log there? It would be simple to implement and maintain, and give some transparency to users.

I also agree logging once might be a good idea.

**Comment by tonynajjar** [comment]
cross-linking as this seems related: https://github.com/ros2/rclcpp/pull/2343

**Comment by fujitatomoya** [comment]
@tonynajjar thanks, i was going to do that, but dropped it from my radar. we need to implement it in rclpy as counterpart of https://github.com/ros2/rclcpp/pull/2343

**Comment by fujitatomoya** [comment]
@tonynajjar @apockill if you can review https://github.com/ros2/rclpy/pull/1292, that would be appreciated!

**Comment by fujitatomoya** [comment]
@apockill @tonynajjar https://github.com/ros2/rclpy/pull/1292 has been merged in rclpy, so that we can get the `TimerInfo` in the application timer callback. i will go ahead to close this one.
