### ISSUE TITLE
Can we add `rclpy.wait_for_message()` for ros **galactic** branch? Like #960 did for ros2-rolling

### ISSUE THREAD

**Issue by GoroYeh-HRI** [ros2/rclpy#1162]
As title, could we add the function "wailt_for_message()" to ros2 galactic distro? 
Thank you!

**Comment by clalancette** [comment]
> As title, could we add the function "wailt_for_message()" to ros2 galactic distro? Thank you!

No, sorry.  Galactic is now [End-of-Life](http://docs.ros.org/en/rolling/Releases.html), so we won't be doing any further updates to it.
