### ISSUE TITLE
A super easy way to successfully setup ROS2 under WSL

### ISSUE THREAD

**Issue by AnarchistKnight** [ros2/rclpy#1375]
After several trials, I finally succeed in setuping ROS2 under WSL. I would like to share how, hoping this would help those who are new to ROS2.

## 1. Install WSL Ubuntu 22.04
Go [this](https://apps.microsoft.com/detail/9pn20msr04dw?hl=en-US&gl=US) page to download and install. Install Ubuntu of other version would almost certainly lead to to setup failure. Also, you can also install WSL by open Windows cmd and type in
</head>
<body>
<div class="code-box">
<pre>
wsl --install -d Ubuntu-22.04
</pre>
</div>
</body>
</html>

## 2. Open Ubuntu terminal
After WSL install, search "Ubuntu" in Windows startup menu and open.

## 3. Install ROS2 Iron Irwini. 
Here "Iron Irwini" is the so-called distro, which in some way is short for distribution. ROS2 Iron Irwini is the one that is most recommended on Ubuntu Linux 22.04 among all distributions. See [here](https://www.ros.org/blog/getting-started/) for more info.

To download the binary file, in the opened Ubuntu terminal type in
</head>
<body>
<div class="code-box">
<pre>
wget https://github.com/ros2/ros2/releases/download/release-iron-20240712/ros2-iron-20240712-linux-jammy-amd64.tar.bz2
</pre>
</div>
</body>
</html>

## 4. To Finish
The rest can be done by following the offical instruction [here.](https://docs.ros.org/en/iron/Installation/Alternatives/Ubuntu-Install-Binary.html), but make two revises to the official instruction.

### 4.1
The first one, change 
</head>
<body>
<div class="code-box">
<pre>
tar xf ~/Downloads/ros2-package-linux-x86_64.tar.bz2
</pre>
</div>
</body>
</html>
 to 
</head>
<body>
<div class="code-box">
<pre>
tar xf ../ros2-iron-20240712-linux-jammy-amd64.tar.bz2
</pre>
</div>
</body>
</html>

### 4.2
The second one, change 
</head>
<body>
<div class="code-box">
<pre>
rosdep update
</pre>
</div>
</body>
</html>
 to 
</head>
<body>
<div class="code-box">
<pre>
rosdep update --include-eol-distros
</pre>
</div>
</body>
</html>
 to enable updating end-of-life distros.

## 5. Verify
try 'ros2 run demo_nodes_cpp talker' and you would see output like below.

![image](https://github.com/user-attachments/assets/547a760b-d5a4-423a-9232-70ad0e4005d4)

**Comment by clalancette** [comment]
Thanks for this writeup.  This seems like it is all in the official documentation, except for:

> rosdep update --include-eol-distros

This shouldn't be necessary; Iron is still one of the supported distributions.  What happens if you don't do that?

Given that there is no real action to be taken here, I'm going to close this out, but feel free to reopen or keep commenting if you want to change something.
