### ISSUE TITLE
rclpy import issue

### ISSUE THREAD

**Issue by karesh** [ros2/rclpy#153]
>>> import rclpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/ros/r2b3/lib/python3.5/site-packages/rclpy/__init__.py", line 26
    def init(*, args=None):
              ^
SyntaxError: invalid syntax
>>> 
 system ubuntu 16.04

**Comment by mikaelarguedas** [comment]
@karesh Please make sure you use python3. This looks like a python2 error

**Comment by mikaelarguedas** [comment]
closing this due to no response.
@karesh please comment here if you're still facing this issue and we can reopen
