### ISSUE TITLE
revisit futures

### ISSUE THREAD

**Issue by dirk-thomas** [ros2/rclpy#200]
Based on the discussion in #199 it needs to be ensured that exceptions are visible.

**Comment by sloretz** [comment]
[Link to discussion](https://github.com/ros2/rclpy/pull/199#discussion_r198976557)

**Comment by sloretz** [comment]
I think this ticket was fixed by #412. The original discussion was about making `result()` raise exceptions if an exception was set instead of a result. Closing.
