### ISSUE TITLE
revisit GET_LIST_READY_ENTITIES

### ISSUE THREAD

**Issue by dirk-thomas** [ros2/rclpy#201]
Follow up of #197.

When `PyLong_FromUnsignedLongLong` return `NULL` it should be reported somehow. If `NULL` is returned it needs to be ensured that it is handled correctly by all callers. Also the return value of `PyList_Append` should be checked.

**Comment by sloretz** [comment]
Partial duplicate of #139 ?

**Comment by mikaelarguedas** [comment]
closing as duplicate of #139
