### ISSUE TITLE
"AttributeError: 'Time' object has no attribute 'nanoseconds'" when using message_filters

### ISSUE THREAD

**Issue by ahuizxc** [ros2/rclpy#241]
## Bug report

**Required Info:**

- Operating System:
  - 
- Installation type:
  - 
- Version or commit hash:
  - 
- DDS implementation:
  - 
- Client library (if applicable):
  - 

#### Steps to reproduce issue

```
when using message_filters python package, 
I got AttributeError: 'Time' object has no attribute 'nanoseconds', this caused by my rclcpp version isn't match the message_filter version, 
so i tried latest-release branch, but it also doesn't have this  modul.
 At last, I tried the master branch which has "nanoseconds", but the compilation was not successful. 
```

#### Additional information

----

**Comment by mikaelarguedas** [comment]
Thanks @ahuizxc for reporting. Please fill out the issue template with all the requested information and steps to reproduce the issue

**Comment by ahuizxc** [comment]
just want to know which branch should i use if i want to use the time module :) thanks~

**Comment by dirk-thomas** [comment]
Please include exact information as outlined in the issue template: what you are using (links to repos including the branch name), your platform, what you are doing and a 1-to-1 of the error message / stacktrace you are seeing.

**Comment by ahuizxc** [comment]
when i want to use the clock module, i got the error:

    from rclpy.clock import ROSClock
ModuleNotFoundError: No module named 'rclpy.clock'

**Comment by dirk-thomas** [comment]
Assuming that you are using the latest release (which you haven't been able to clarify) this is expected since the Python module `rclpy.clock` has been added after the latest release. You will need to use the latest code from the master branch to use this feature.

I will go ahead and close the ticket.

**Comment by ahuizxc** [comment]
when i use the latest code from the master branch, i got this error:

src/ros2/rclpy/rclpy/src/rclpy/_rclpy.c:1210:61: error: incompatible type for argument 4 of ‘rcl_timer_init’
   rcl_ret_t ret = rcl_timer_init(timer, clock, period_nsec, NULL, allocator);

**Comment by dirk-thomas** [comment]
> when i use the latest code from the master branch, i got this error:

What version of the dependencies are you trying to use, e.g. `rcl`?
