### ISSUE TITLE
[action server] better error handling when execute callback fails

### ISSUE THREAD

**Issue by stonier** [ros2/rclpy#296]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 18.04
- Installation type:
  - binaries
- Version or commit hash:
  - crystal
- DDS implementation:
  - default
- Client library (if applicable):
  - rclpy

#### Steps to reproduce issue

1. Run [minimal_action_server/examples_rclpy_minimal_action_server/server.py](https://github.com/ros2/examples/blob/master/rclpy/actions/minimal_action_server/examples_rclpy_minimal_action_server/server.py)
2. Run [minimal_action_client/examples_rclpy_minimal_action_client/client.py](https://github.com/ros2/examples/blob/master/rclpy/actions/minimal_action_client/examples_rclpy_minimal_action_client/client.py)

All is good.

3. Edit [minimal_action_server/examples_rclpy_minimal_action_server/server.py](https://github.com/ros2/examples/blob/master/rclpy/actions/minimal_action_server/examples_rclpy_minimal_action_server/server.py) and add the following lines in the middle of `execute_callback(...)`:
```
    if i == 3:
        print(self.foo)
```
4. Start the server
5. Start the client

#### Expected behavior

How this should be handled is up for debate, but at the very least, the user is notified  _immediately_ that there is a problem with useful details for debugging (i.e. `AttributeError` and backtrace get to the user). Should the action server gracefully recover (i.e. clean up and send a result response back to the client)?

#### Actual behavior

* Hangs.
* Upon CTRL-C, the server finally exits and reports:

```
The following exception was never retrieved: 'MinimalActionServer' object has no attribute 'foo'
```

**Comment by jacobperron** [comment]
Fix proposed in #437. I think it's a good thing to backport as well.
