### ISSUE TITLE
increasing memory usage of talker

### ISSUE THREAD

**Issue by dirk-thomas** [ros2/rclpy#302]
This can easily be reproduced with the `demo_nodes_py` `talker`.

To make the increasing memory usage more noticeable bump the publishing frequency to 50 Hz. Even with the actual publisher / publishing and message commented out the memory usage keeps increasing steadily.

The C++ equivalent doesn't seem to have the same problem.

**Comment by tfoote** [comment]
Possibly related, just looping on a timer callback also is reported to leak without even publishing: https://answers.ros.org/question/320851/ros2-serious-memory-leak-when-using-timer/

**Comment by dirk-thomas** [comment]
It isn't just related but exactly what is being reported in this ticket.
