### ISSUE TITLE
Publishing a message of the wrong type can cause a hard error

### ISSUE THREAD

**Issue by rotu** [ros2/rclpy#314]
## Bug report

**Required Info:**

- Operating System:
  - Windows 10
- Installation type:
  - binaries
- Version or commit hash:
  - 
- DDS implementation:
  - 
- Client library (if applicable):
  - rclpy

#### Steps to reproduce issue
```
import rclpy
rclpy.init()
import std_msgs.msg

n = rclpy.create_node('mynode')
p = n.create_publisher(std_msgs.msg.UInt32,'mytopic')
p.publish(42)
```
#### Expected behavior
Either the value is converted silently to the compatible message type or a catchable error is thrown.

#### Actual behavior
The python interpreter crashes and the following is found in Event Viewer:
```
Faulting application name: python.exe, version: 3.7.3150.1013, time stamp: 0x5c9954fa
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x0000000000000000
Faulting process id: 0x73b0
Faulting application start time: 0x01d4f4e426ff3935
Faulting application path: C:\Python37\python.exe
Faulting module path: unknown
Report Id: 682bc596-629a-4933-962f-ffe339ad65c1
Faulting package full name: 
Faulting package-relative application ID: 
```

#### Additional information

In the file publisher.py, there should probably be a check `isinstance(msg, self.msg_type)` or `type(msg) is self.msg_type` and a TypeError thrown.

**Comment by dirk-thomas** [comment]
Thanks for the report. PR #317 address this for publishing messages as well as various other API.

In the future when you have a specific proposal please consider to create a pull request for it.
