### ISSUE TITLE
import messages before calling rclpy.init

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/rclpy#36]
modify typesupport import logic to allow message import before chosing rclpy implementation

**Comment by mikaelarguedas** [comment]
@dirk-thomas do you think that this classmethod approach is a suitable solution to allow importing the typesupport at subscription/publication time ?

**Comment by mikaelarguedas** [comment]
seems to have introduced [a single test failure](http://ci.ros2.org/job/ci_linux/1488/testReport/junit/(root)/test_publisher_subscriber_python__Primitives__rmw_opensplice_cpp_/test_publisher_subscriber/)

running repeated tests to see if the `proxy participant unknown` warning is related. 
[![Build Status](http://ci.ros2.org/job/ci_linux/1491/badge/icon/)](http://ci.ros2.org/job/ci_linux/1491)

**Comment by mikaelarguedas** [comment]
Failure did not reappear.
Linux: [![Build Status](http://ci.ros2.org/job/ci_linux/1493//badge/icon/)](http://ci.ros2.org/job/ci_linux/1493/)
OSX: [![Build Status](http://ci.ros2.org/job/ci_osx/1155/badge/icon/)](http://ci.ros2.org/job/ci_osx/1155)
Windows job failed while trying to delete the workspace before building. Will try again on windshield soon

**Comment by mikaelarguedas** [comment]
@ros2/ros2_team please review

**Comment by dirk-thomas** [comment]
+1 for the referenced PRs.

As discussed offline in the future this could be refactored to avoid that the Python code has to deal with it (check the class variables, call a function which populates them, and then pull the content of the variables in C again). Instead the C code should be able to access the information directly.
