### ISSUE TITLE
rosdep fails while installing ros2 (crystal)in ubuntu xenial 16.04

### ISSUE THREAD

**Issue by Narendarselva** [ros2/rclpy#361]
facing issue while installing rosdep .

root@dcrt-lnx-2:/home/Naren/ros2_ws# rosdep install --from-paths src --ignore-src --rosdistro crystal -y --skip-keys "console_bridge fastcdr fastrtps libopensplice67 libopensplice69 python3-lark-parser rti-connext-dds-5.3.1 urdfdom_headers" 

ERROR: the following packages/stacks could not have their rosdep keys resolved to system dependencies: test_cli_remapping: No definition of [python_cmake_module] for OS version [xenial] rosidl_default_runtime: No definition of [rosidl_generator_py] for OS version [xenial] test_cli: No definition of [python_cmake_module] for OS version [xenial] rclpy: No definition of [rosidl_generator_py] for OS version [xenial] test_communication: No definition of [python_cmake_module] for OS version [xenias

**Comment by sloretz** [comment]
Hi @Narendarselva, this question fits better on https://answers.ros.org .Thank you for already creating one: https://answers.ros.org/question/324069/rosdep-fails-while-installing-ros2-crystalin-ubuntu-xenial-1604/
