### ISSUE TITLE
Rename QoS*Policy enum's to *Policy

### ISSUE THREAD

**Issue by sloretz** [ros2/rclpy#371]
#### Feature description

The QoS policy classes all [start with QoS](https://github.com/ros2/rclpy/blob/0be24021af4269ce7c83fe9db550e326a8428a9b/rclpy/rclpy/qos.py#L259-L318). `QoS` is a bit annoying to type because of the case change, and it is redundant since they're in a module named `qos` (ex: `from rclpy.qos import QoSHistoryPolicy`).

This is a proposal to rename them:

* `QoSHistoryPolicy` -> `HistoryPolicy`
* `QoSReliabilityPolicy` -> `ReliabilityPolicy`
* `QoSDurabilityPolicy` -> `DurabilityPolicy`
* `QoSLivelinessPolicy` -> `LivelinessPolicy`

#### Implementation considerations
Since there is some code using these names already, there would be no cost to changing the class names and adding module variables with the old names.

```python3
class HistoryPolicy(QoSPolicyEnum): 
# ...

QoSHistoryPolicy = HistoryPolicy
```

**Comment by suab321321** [comment]
I would like to help with this issue...this is my first time..so can you tell me how to proceed
