### ISSUE TITLE
Add `get_parameters_by_prefix` method

### ISSUE THREAD

**Issue by ivanpauno** [ros2/rclpy#374]
#### Feature description
It should work in the same way as the `rclcpp` counterpart:
https://github.com/ros2/rclcpp/blob/e7c463dc74849aa64cb8a74e13f2a57b4ed59862/rclcpp/include/rclcpp/node.hpp#L783-L787

See [discussion](https://github.com/ros/joint_state_publisher/pull/16#discussion_r296263399).

**Comment by ivanpauno** [comment]
@jubeira Could you take a look?
If not, I can give it a try.

**Comment by jubeira** [comment]
I can check this once #377 gets through.
