### ISSUE TITLE
qos support

### ISSUE THREAD

**Issue by geoffviola** [ros2/rclpy#38]
It seems that the qos settings are not available in rclpy: https://github.com/ros2/rclpy/blob/master/rclpy/src/rclpy/_rclpy.c#L63. Is this true? When might such a feature be included?

**Comment by wjwwood** [comment]
No, it's not supported yet. The Python interface is under active development and we hope to add the remaining features (like QoS) and functions (like `count_publishers` and friends) soon.

@mikaelarguedas fyi
