### ISSUE TITLE
Avoid exception when ctrl-c 

### ISSUE THREAD

**Issue by Karsten1987** [ros2/rclpy#398]
## Bug report

This issue is mainly motivated by https://github.com/ros-visualization/rqt/issues/198
When quitting a GUI application, such as `rqt_gui` by either closing it through the window button or `ctrl-c` it, I see a traceback of an uncaught exception regarding the waitset.

**Required Info:**

- Operating System:
  - OSX
- Installation type:
  - N/A
- Version or commit hash:
  - dashing and master

#### Steps to reproduce issue
Closing a RQT gui application

#### Expected behavior
GUI application closes correctly.

#### Actual behavior
```
Traceback (most recent call last):
  File "/Users/karsten/workspace/osrf/ros2_full/build/rqt_gui_py/src/rqt_gui_py/rclpy_spinner.py", line 32, in run
    executor.spin_once(timeout_sec=1.0)
  File "/Users/karsten/workspace/osrf/ros2_full/install/lib/python3.7/site-packages/rclpy/executors.py", line 695, in spin_once
    handler, entity, node = self.wait_for_ready_callbacks(timeout_sec=timeout_sec)
  File "/Users/karsten/workspace/osrf/ros2_full/install/lib/python3.7/site-packages/rclpy/executors.py", line 649, in wait_for_ready_callbacks
    return next(self._cb_iter)
  File "/Users/karsten/workspace/osrf/ros2_full/install/lib/python3.7/site-packages/rclpy/executors.py", line 532, in _wait_for_ready_callbacks
    self._context.handle)
RuntimeError: Failed to initialize wait set: the given context is not valid, either rcl_init() was not called or rcl_shutdown() was called., at /Users/karsten/workspace/osrf/ros2_full/src/ros2/rcl/rcl/src/rcl/wait.c:130
```
#### Additional information
There is a try to "fix" this by catching the exception and thus suppressing the traceback. 
See here: https://github.com/ros-visualization/rqt/pull/199

However, I believe the root cause of this issue might lie in rclpy.

**Comment by ivanpauno** [comment]
A simpler repro of the bug:

```python3
import threading
import time
import rclpy
from rclpy.node import Node


def kill():
    print('waiting')
    time.sleep(5)
    print('shutting down')
    rclpy.shutdown()


def main(args=None):
    rclpy.init(args=args)

    node = Node('asd')

    thread = threading.Thread(target=kill)
    thread.start()

    print('spinning')
    rclpy.spin(node)

    node.destroy_node()
    rclpy.shutdown()


if __name__ == '__main__':
    main()
```

Basically, you can't shutdown `rclpy` from another thread.

`rqt_gui_py` is doing that:
https://github.com/ros-visualization/rqt/blob/3911625f95cc14a751c91fa2712d78ab1a6854cc/rqt_gui_py/src/rqt_gui_py/ros_py_plugin_provider.py#L81-L85

I believe `rclpy` signal handler is not being called, as `qt_gui` is overriding sigint handler (without chaining):

https://github.com/ros-visualization/qt_gui_core/blob/3d9de6ca2be2be38cfe561f7fe6fdc3744184dc4/qt_gui/src/qt_gui/main.py#L461-L464

I will try to dig a little bit more (and maybe solve the problem).
