### ISSUE TITLE
Strange behavior with rclpy and multiprocess

### ISSUE THREAD

**Issue by esteve** [ros2/rclpy#4]
If rclpy is imported globally, subprocesses don't seem to be able to access the underlying extensions.

**Comment by mikaelarguedas** [comment]
@esteve @clalancette Is it possible to provide a code snippet to reproduce this issue for the time we address it ?

**Comment by dirk-thomas** [comment]
I will close this ticket for now since it doesn't contain enough information to act on it. Please feel free to comment with more information and this ticket can be reopened.
