### ISSUE TITLE
doubt in validating parameter names in rclpy

### ISSUE THREAD

**Issue by suab321321** [ros2/rclpy#406]
@nuclearsandwich @sloretz @ivanpauno  #380 

I am working on issue #380.I have two doubts in that:
1.There is no defined constraints for parameters names like the ones mentioned in doc for node and topic name validation
2.According to me I should implement this validation of parameters in rcl repository and then import the file in _rclpy.c and from here I should use the functionality for validation.Am I correct?

**Comment by jubeira** [comment]
Hi @suab321321,
I've replied your question in #380; please keep the discussion in the same ticket so that it's easier to follow-up.
Thanks!

**Comment by suab321321** [comment]
Sorry for this mistake @jubeira.
