### ISSUE TITLE
rclpy.time to_msg function taking a lot of time to execute

### ISSUE THREAD

**Issue by sudo-panda** [ros2/rclpy#409]
https://github.com/ros2/rclpy/blob/8da91cee54b68f1108ca017da885496ffb5ae16c/rclpy/rclpy/time.py#L138
It is taking a lot of to retrieve the current time when using the Time object and converting it to Time msg.

**Comment by clalancette** [comment]
No reply to this one in a long time, so I'm going to close it out.  Feel free to reopen if you are still having issues.
