### ISSUE TITLE
Parameter constructor should accept ParameterValue with array.array types

### ISSUE THREAD

**Issue by gonzodepedro** [ros2/rclpy#424]
## Bug report

**Required Info:**

- Operating System:
  - All
- Installation type:
  - All
- Version or commit hash:
  - Dashing repos
- DDS implementation:
  - all
- Client library (if applicable):
  - rclpy

#### Steps to reproduce issue

Parameter.from_parameter_msg(ParameterMsg(name="Message", value = ParameterValue(type=7, int_array_value=[55,25,35]))

#### Expected behavior

A parameter is created with the information provided

#### Actual behavior

ValueError: Type 'Type.INTEGER_ARRAY' and value 'array('q', [640, 480])' do not agree

#### Additional information

Parameter constructor does type validation by calling the check() method in the Parameter.Type class. This method doesn't support array.array values.

**Comment by ivanpauno** [comment]
I have been able to reproduce the issue with the following script:
```python3
from rclpy.parameter import Parameter
from rcl_interfaces.msg import Parameter as ParameterMsg
from rcl_interfaces.msg import ParameterValue

Parameter.from_parameter_msg(
    ParameterMsg(
        name="Message",
        value=ParameterValue(type=7, integer_array_value=[55,25,35])))
```

There are two possible solutions:
- Accept `array.array` as a parameter value, doing something similar to https://github.com/ros2/rclpy/pull/389.
- Convert from `array.array` to `tuple` or `list` in `from_parameter_msg` classmethod.

I would rather go with the first option.
