### ISSUE TITLE
action client send_goal() must call send_goal_async(goal, kwargs) with **kwargs

### ISSUE THREAD

**Issue by werner-ne** [ros2/rclpy#446]
## Bug report

action client send_goal() (line 367) must call send_goal_async(goal, kwargs) with **kwargs instead

**Comment by sloretz** [comment]
https://github.com/ros2/rclpy/blob/11ecd21f098a19df4fa40af174c1367c6eab7d68/rclpy/rclpy/action/client.py#L367

@werner-ne Thanks for the report. Would you mind opening a PR with a fix?

**Comment by jacobperron** [comment]
Here's an example reproducing the bug: https://github.com/ros2/examples/pull/254

**Comment by werner-ne** [comment]
not sure if I did the pull request properly?

**Comment by jacobperron** [comment]
> not sure if I did the pull request properly?

@werner-ne the change looks good, but you should change the target of the pull request to this repository (instead of your fork).
