### ISSUE TITLE
Ability to configure domain ID in rclpy

### ISSUE THREAD

**Issue by fujitatomoya** [ros2/rclpy#484]
#### Feature description

ability to set the Domain ID on a per-node basis.

the same ability with https://github.com/ros2/rclcpp/issues/910

#### Implementation considerations

1. add domain id with rclpy Node Class option. (default RCL_NODE_OPTIONS_DEFAULT_DOMAIN_ID)
2. if it is RCL_NODE_OPTIONS_DEFAULT_DOMAIN_ID, the rcl overrides domain id with ROS_DOMAIN_ID environmental variable.

**Comment by fujitatomoya** [comment]
related to https://github.com/ros2/rclcpp/issues/910

**Comment by ivanpauno** [comment]
Closing, as I think it has been clarified in https://github.com/ros2/rclcpp/issues/910#issuecomment-566520259.
Please, reopen if not.

**Comment by fujitatomoya** [comment]
@ivanpauno 

this is for the same ability with https://github.com/ros2/rclcpp/issues/910 for rclpy. i believe that this is needed for rclpy also not only for rclcpp.

**Comment by ivanpauno** [comment]
> @ivanpauno
> 
> this is for the same ability with [ros2/rclcpp#910](https://github.com/ros2/rclcpp/issues/910) for rclpy. i believe that this is needed for rclpy also not only for rclcpp.

Sorry, I didn't understand that.
The title sounds like rclpy is not using `ROS_DOMAIN_ID` environment variable.
Can you update the description and reopen? Thanks!

**Comment by fujitatomoya** [comment]
@ivanpauno 

> The title sounds like rclpy is not using ROS_DOMAIN_ID environment variable.

my bad, that confuses you.

> Can you update the description and reopen? Thanks!

will do it right now.

**Comment by suab321321** [comment]
@ivanpauno sir I would like to contribute to this.

**Comment by ivanpauno** [comment]
For the same reason than here https://github.com/ros2/rclcpp/issues/910#issuecomment-555000410, it's better to wait now. The other set of PRs will be done soon, after that, this will be unblocked.

**Comment by fujitatomoya** [comment]
@ivanpauno 

this one too, you can leave it to us.

**Comment by Barry-Xu-2018** [comment]
@ivanpauno @fujitatomoya 

After checking current implementation of rclpy, it only supports use default rcl_opitions.   

https://github.com/ros2/rclpy/blob/8f601c69ce9775ee3764c2bcfa2cd22cd9c31a1d/rclpy/src/rclpy/_rclpy.c#L523-L528

If want to support configuring domain ID, I have to expose InitOption to rclpy.  
What do you think ?

**Comment by fujitatomoya** [comment]
@Barry-Xu-2018 

i think we do need to expose InitOption to rclpy, i think that's the idea.

**Comment by Barry-Xu-2018** [comment]
> @Barry-Xu-2018
> 
> i think we do need to expose InitOption to rclpy, i think that's the idea.

Thank you.

**Comment by Barry-Xu-2018** [comment]
@ivanpauno 

Friendly ping.  
If have time, please look at comment.  https://github.com/ros2/rclpy/issues/484#issuecomment-643233546  
I want to hear your opioin.

**Comment by ivanpauno** [comment]
> @ivanpauno @fujitatomoya
> 
> After checking current implementation of rclpy, it only supports use default rcl_opitions.
> 
> https://github.com/ros2/rclpy/blob/8f601c69ce9775ee3764c2bcfa2cd22cd9c31a1d/rclpy/src/rclpy/_rclpy.c#L523-L528
> 
> If want to support configuring domain ID, I have to expose InitOption to rclpy.
> What do you think ?

Prefer adding an extra keyword argument to the functions with a default:

https://github.com/ros2/rclpy/blob/7116fb4eb51282f706a361ebb25928ee8e0eda3f/rclpy/rclpy/__init__.py#L62
https://github.com/ros2/rclpy/blob/7116fb4eb51282f706a361ebb25928ee8e0eda3f/rclpy/rclpy/context.py#L36

Both should have a new `, domain_id: int = get_default_domain_id()` argument.

In `_rclpy.c`, you will need to write a new `rclpy_get_default_domain_id` function, and extend `rclpy_init` signature with an extra argument.

**Comment by Barry-Xu-2018** [comment]
> > @ivanpauno @fujitatomoya
> > After checking current implementation of rclpy, it only supports use default rcl_opitions.
> > https://github.com/ros2/rclpy/blob/8f601c69ce9775ee3764c2bcfa2cd22cd9c31a1d/rclpy/src/rclpy/_rclpy.c#L523-L528
> > 
> > If want to support configuring domain ID, I have to expose InitOption to rclpy.
> > What do you think ?
> 
> Prefer adding an extra keyword argument to the functions with a default:
> 
> https://github.com/ros2/rclpy/blob/7116fb4eb51282f706a361ebb25928ee8e0eda3f/rclpy/rclpy/__init__.py#L62
> 
> 
> https://github.com/ros2/rclpy/blob/7116fb4eb51282f706a361ebb25928ee8e0eda3f/rclpy/rclpy/context.py#L36
> 
> Both should have a new `, domain_id: int = get_default_domain_id()` argument.
> 
> In `_rclpy.c`, you will need to write a new `rclpy_get_default_domain_id` function, and extend `rclpy_init` signature with an extra argument.

Thanks for your suggestion.

**Comment by ivanpauno** [comment]
> Both should have a new `, domain_id: int = get_default_domain_id()` argument.

You could also use the number [here](https://github.com/ros2/rcl/blob/b9cfc243bf018091b5c5bcb5585d19591daf4ae6/rcl/include/rcl/domain_id.h#L29) as a default value, and `rcl` will check the environment variable [here](https://github.com/ros2/rcl/blob/b9cfc243bf018091b5c5bcb5585d19591daf4ae6/rcl/src/rcl/init.c#L147-L154).

**Comment by Barry-Xu-2018** [comment]
> > Both should have a new `, domain_id: int = get_default_domain_id()` argument.
> 
> You could also use the number [here](https://github.com/ros2/rcl/blob/b9cfc243bf018091b5c5bcb5585d19591daf4ae6/rcl/include/rcl/domain_id.h#L29) as a default value, and `rcl` will check the environment variable [here](https://github.com/ros2/rcl/blob/b9cfc243bf018091b5c5bcb5585d19591daf4ae6/rcl/src/rcl/init.c#L147-L154).

Thanks. Got it.

**Comment by Barry-Xu-2018** [comment]
@ivanpauno @fujitatomoya 

Please review codes.   
#594

**Comment by fujitatomoya** [comment]
CC: @ivanpauno 

i am closing this since https://github.com/ros2/rclpy/pull/596 is merged.
