### ISSUE TITLE
Timestamp for ROS2 message

### ISSUE THREAD

**Issue by JasonACDsouza** [ros2/rclpy#506]
Sorry for the silly question but I am new to the concept of Clock in ROS2 and trying real hard to understand it, I was wondering if there is a straighforward way to get the timestamp of ros2 messages from playing the rosbags? If not, how can I record messages with associating system time to them?

**Comment by mjcarroll** [comment]
Per our [Support Guidelines](https://wiki.ros.org/Support), this type of question is best asked on answers.ros.org

We like to keep answers and questions all in one place so it is easy to search later.
