### ISSUE TITLE
When I import msg, ide reminds me a error

### ISSUE THREAD

**Issue by YoJn** [ros2/rclpy#507]
## Code structure

![Code structure](https://user-images.githubusercontent.com/41852511/74099412-7cbd2100-4b5e-11ea-9639-4b856a668449.png)

In my project, I put rclpy and B rcl_interface together, because rclpy import some code from rcl_interface .

## Error

![QQ截图20200209170815](https://user-images.githubusercontent.com/41852511/74099440-ca398e00-4b5e-11ea-9dfb-aee1e333019f.png)

ide can find that package, but can not find that data structure.

What should I do? Thanks for your help!

**Comment by YoJn** [comment]
![QQ截图20200209170815](https://user-images.githubusercontent.com/41852511/74099532-ceb27680-4b5f-11ea-9bcf-87ea2c6f04c3.png)

**Comment by tfoote** [comment]
It looks like you have action_msgs in your source tree. As such the messages will be generated when you run the build. Until then your IDE won't be able to find the definition as the python version has not been generated. So after you run the build once hopefully your IDE will pick up the generated python code. Until then it's likely that you won't be able to resolve the issue. 

Another option would be to have the action_msgs in an underlay workspace that you build from source or install from binaries the default version.

**Comment by YoJn** [comment]
> It looks like you have action_msgs in your source tree. As such the messages will be generated when you run the build. Until then your IDE won't be able to find the definition as the python version has not been generated. So after you run the build once hopefully your IDE will pick up the generated python code. Until then it's likely that you won't be able to resolve the issue.
> 
> Another option would be to have the action_msgs in an underlay workspace that you build from source or install from binaries the default version.

Thanks for your help, but I still don't know how to build it.  Does it need me to take the msg files to convert python files? Although I don't know how to convert. 

[abcrclpy.zip](https://github.com/ros2/rclpy/files/4183845/abcrclpy.zip)

**Comment by tfoote** [comment]
Yes, you need to have the generators convert the msg files to python. It's done as part of the build. Your package already has the interfaces declared and will generate them you just have to build it.

Please read through the tutorials at: https://index.ros.org/doc/ros2/Tutorials/

In particular: https://index.ros.org/doc/ros2/Tutorials/Colcon-Tutorial/

If you need more help please open a question on https://answers.ros.org with enough information to reproduce your problem there. We try to keep the trackers for development discussions.
