### ISSUE TITLE
Timer related tests experience more jitter on windows

### ISSUE THREAD

**Issue by brawner** [ros2/rclpy#513]
`test_rate.py` fails periodically on ci_windows-container builds, but I think it is also an issue on ci_windows as well. The jitter in the Rate period is about 0.01 seconds, which also happens to be the `max_jitter criteria`. I printed out the measurements so you can get idea of the ranges for the different build systems. 

The strange thing that maybe someone can illuminate is why the period measurements are very precisely 0.094s and 0.011s. 

I don't think the actual issue is in rclpy. If someone can help shed light on this, I can keep trying to dig into this issue.

https://ci.ros2.org/job/ci_linux/9412/testReport/rclpy.src.ros2.rclpy.rclpy.test.test_rate/TestRate/test_rate_valid_period/
https://ci.ros2.org/job/ci_windows/9327/testReport/rclpy.src.ros2.rclpy.rclpy.test.test_rate/TestRate/test_rate_valid_period/
https://ci.ros2.org/job/ci_windows-container/184/testReport/junit/(root)/projectroot/test_rate/
https://ci.ros2.org/job/ci_linux-aarch64/5090/testReport/rclpy.src.ros2.rclpy.rclpy.test.test_rate/TestRate/test_rate_valid_period/
https://ci.ros2.org/job/ci_osx/7699/testReport/junit/rclpy.src.ros2.rclpy.rclpy.test.test_rate/TestRate/test_rate_valid_period/

More examples:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=9414)](http://ci.ros2.org/job/ci_linux/9414/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=5092)](http://ci.ros2.org/job/ci_linux-aarch64/5092/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=7701)](http://ci.ros2.org/job/ci_osx/7701/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9329)](http://ci.ros2.org/job/ci_windows/9329/)
* Windows-container [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows-container&build=186)](http://ci.ros2.org/job/ci_windows-container/186/)

Possible related issue:
https://github.com/ros2/rclpy/issues/267

**Comment by brawner** [comment]
Updating to reflect that this also affects the test_timer.py 100Hz tests. Windows can handle 10Hz, but gets flakey on 100Hz.

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=9428)](http://ci.ros2.org/job/ci_linux/9428/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=5109)](http://ci.ros2.org/job/ci_linux-aarch64/5109/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=7709)](http://ci.ros2.org/job/ci_osx/7709/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9346)](http://ci.ros2.org/job/ci_windows/9346/)
* Windows-container [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows-container&build=200)](http://ci.ros2.org/job/ci_windows-container/200/)

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/windows-ci-builds-are-now-officially-containerized-and-virtualized-on-ci-ros2-org/13099/4

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-2-tsc-meeting-minutes-2020-03-18/13313/1
