### ISSUE TITLE
Add default Incompatible QoS callbacks

### ISSUE THREAD

**Issue by mm318** [ros2/rclpy#533]
#### Feature description

With https://github.com/ros2/rclpy/pull/459 merged in, a user is able to provide a callback for when an participant on the topic is discovered but unable to be matched due to incompatible QoS policies. This feature request is for leveraging this feature even when a user does not provide a custom callback function, by setting a default callback function that prints a warning (initially suggested at https://github.com/ros2/ros2/issues/822#issuecomment-598024481) on the discovery of an incompatible participant on the topic.

#### Implementation considerations

What should the behavior be if the underlying middleware does not support this kind of QoS event callback?

**Comment by hidmic** [comment]
@mm318 are you looking forward to implement this feature?

**Comment by mm318** [comment]
Hi @hidmic, we already have a pull request opened for this at https://github.com/ros2/rclpy/pull/536.

**Comment by mm318** [comment]
Closing this issue as the related pull request has been merged.
