### ISSUE TITLE
Test `test_logging_rosout.py` is flaky

### ISSUE THREAD

**Issue by ivanpauno** [ros2/rclpy#546]
See https://github.com/ros2/rclpy/pull/469#discussion_r414247845.

Example of a job in CI failing: https://ci.ros2.org/job/ci_osx/8540/testReport/rclpy.src.ros2.rclpy.rclpy.test/test_logging_rosout/test_enable_rosout_enable_global_rosout_enable_node_rosout_True_True_True_/.

**Comment by Barry-Xu-2018** [comment]
@ivanpauno 

Please assign this issue to me. Thanks.

**Comment by Barry-Xu-2018** [comment]
@ivanpauno 

Refer to test_node.py, I updated codes.  
Please review #548  
If you have good idea, please let me know.

**Comment by Barry-Xu-2018** [comment]
@ivanpauno  

#548 has been merged.  
This issue can be closed.

**Comment by ivanpauno** [comment]
Thanks @Barry-Xu-2018 !
