### ISSUE TITLE
Callback service in other callback

### ISSUE THREAD

**Issue by matthijsramlab** [ros2/rclpy#567]
I do not know if I am the only having trouble with the following: 

I need to create a service that checks if something device is OK. So in the callback it will need to get some information of the device (through a service call), process it and check if it is OK. I am aware that if you would preform a service callback, you will cause a dead lock. So in the docs it says the following: 

_In general, callbacks should only perform light and fast operations._

and 

_The future can also be retrieved using a timer or callback, like in this example, a dedicated thread, or by another method. It is up to you, as the caller, to decide how to store future, check on its status, and retrieve your response._

This I am able to do, however than I need to return a message directly before I got the device information. What would be the preferred approach to tackle this?

**Comment by hidmic** [comment]
@matthijsramlab this kind of questions are usually better suited for [answers.ros.org](https://answers.ros.org/), where the community at large can help you and others can benefit from that exchange. I encourage you to continue the discussion over there. For the time being, I'll close this as it's a non-issue.

> What would be the preferred approach to tackle this?

As you know already, recursive spinning isn't supported. I think that an `rclpy.executors.MultiThreadedExecutor` and blocking client calls should help your use case.
