### ISSUE TITLE
Feature Request: Managed Nodes

### ISSUE THREAD

**Issue by driftregion** [ros2/rclpy#604]
#### Feature description
Able to create [managed nodes](http://design.ros2.org/articles/node_lifecycle.html)

It looks like this includes at least:
- c bindings to [`rcl_lifecycle`](https://github.com/ros2/rcl/tree/master/rcl_lifecycle)
- Python `LifecycleNode` subclass of `rclpy.node.Node`

**Comment by ivanpauno** [comment]
I'm planning to start and implementation of this soon.

> Python LifecycleNode subclass of rclpy.node.Node

To avoid the `rclcpp` issue of `LifecycleNode` getting out of date (not matching the `Node` api), I'm planning to use a mixin (basic summary of what a mixin is [here](https://stackoverflow.com/questions/533631/what-is-a-mixin-and-why-are-they-useful)).

**Comment by scpeters** [comment]
a draft pull request is here: https://github.com/ros2/rclpy/pull/865

**Comment by scpeters** [comment]
demo: https://github.com/ros2/demos/pull/547
