### ISSUE TITLE
Node has no attribute create_rate

### ISSUE THREAD

**Issue by aqieez** [ros2/rclpy#609]
I am using ROS2 crystal on ubuntu 18.04 LTS with the ROS2 web bridge. Everything works fine. But I want to set the data publishing rate, for example, publish 2 messages per 10 seconds. I notice there is a create_rate function in rclpy. But when I try this function every time error pops up Node has no attribute create_rate. I spend 5 hours looking on internet and on https://discourse.ros.org/ and https://answers.ros.org/questions. Got no luck. Below is code 
`

import rclpy

from std_msgs.msg import Int32

def main(args=None):
    rclpy.init(args=args)

    node = rclpy.create_node('sos_publisher')
    rate = node.create_rate(2.0)
    publisher = node.create_publisher(Int32,'/test')

    msg = Int32()
    
    def timer_callback():
        msg.data = 325
        node.get_logger().info('Publishing  message: "%s"' % msg.data)
        publisher.publish(msg)

    timer_period = 10  # seconds
    timer = node.create_timer(timer_period, timer_callback)

    rclpy.spin(node)

    node.destroy_timer(timer)
    node.destroy_node()
    rclpy.shutdown()

if __name__ == '__main__':
    main()`

**Comment by clalancette** [comment]
I suspect that we added `create_rate` after ROS 2 Crystal.  Regardless, Crystal is no longer supported, so I suggest you try one of the [currently supported distributions](https://index.ros.org/doc/ros2/Releases/) instead.

In the future, please ask questions like this on https://answers.ros.org.  That way they are all in one easily searchable place.  I'm going to close this issue.
