### ISSUE TITLE
test_node failure with rmw_connext_cpp

### ISSUE THREAD

**Issue by brawner** [ros2/rclpy#631]
The test result output is not very helpful, but test_node is failing on the rolling connext-only build.ros2.org job.

http://build.ros2.org/view/Rci/job/Rci__nightly-connext_ubuntu_focal_amd64/106/testReport/(root)/projectroot/test_node/

Trying this out with CI, testing `--packages-select rclpy` with only `rmw_connext_cpp`
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=12721)](http://ci.ros2.org/job/ci_linux/12721/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=10435)](http://ci.ros2.org/job/ci_osx/10435/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=12668)](http://ci.ros2.org/job/ci_windows/12668/)

**Comment by clalancette** [comment]
Going back more than 2 weeks, I can't find an instance of this failing.  So I'm going to assume that it was somehow fixed and close this out.  If it comes back up, we can reopen this or open a new bug.
