### ISSUE TITLE
test_shutdown_wakes_rate fails nightly build

### ISSUE THREAD

**Issue by fujitatomoya** [ros2/rclpy#648]
## Bug report

- Operating System:
  - All
- Installation type:
  - source build
- Version or commit hash:
  - https://github.com/ros2/ros2/commit/32b29971204aee3b10afdfd4bc9dd4efa708439b
- DDS implementation:
  - default (Fast-RTPS)
- Client library (if applicable):
  - rclpy

#### Steps to reproduce issue

I've seen this only CI as followings.

- http://ci.ros2.org/job/ci_linux/13261/
- http://ci.ros2.org/job/ci_linux-aarch64/8188/
- http://ci.ros2.org/job/ci_osx/10975/
- http://ci.ros2.org/job/ci_windows/13290/

#### Expected behavior

Test Success

#### Actual behavior

Test Failure with `ROSInterruptException`

#### Implementation considerations

use `try & except` statement to catch the exception.

**Comment by clalancette** [comment]
It's more than flakey; it failed on all platforms in the nightlies.  Something changed that caused it to fail late last week.  We'll look into it this week.

**Comment by fujitatomoya** [comment]
addressed by https://github.com/ros2/rclpy/pull/649

**Comment by fujitatomoya** [comment]
@clalancette 

i will go ahead to close this since you've already fixed with https://github.com/ros2/rclpy/pull/649 👍
