### ISSUE TITLE
Get current time?

### ISSUE THREAD

**Issue by sidd1** [ros2/rclpy#68]
Is there an equivalent for `rospy.Time.now()` with rclpy? I know I can use the time function and build my own `Time` message for the standard `Header` messages. I want to know if this has already been implemented?

**Comment by mikaelarguedas** [comment]
Unfortunately it is not implemented yet, there is a ticket [tracking this](https://github.com/ros2/ros2/issues/178)
For now the [design](http://design.ros2.org/articles/clock_and_time.html) and the API have been defined but the feature itself has not been implemented yet.

**Comment by sidd1** [comment]
Ah yes I see. I read the design document but could not find an issue here or at `rclcpp`, which threw me off. Thanks! I will close this issue then.

**Comment by stonier** [comment]
For reference, the breadcrumb trail for rclpy's version leads to #186
