### ISSUE TITLE
👨‍🌾 Warning in windows packaging jobs "ignoring '/INCREMENTAL' due to '/LTCG' specification"

### ISSUE THREAD

**Issue by azeey** [ros2/rclpy#687]
## Bug report

**Required Info:**

- Operating System:
  - Windows 10
- Installation type:
  - source
- Version or commit hash:
  - starting from 0ebae0cea78ee63864aea8b70b2962e24f42cb69
- DDS implementation:
  - default
- Client library (if applicable):
  - rclpy

#### Steps to reproduce issue

There is a new warning in the windows packaging jobs:
```
   Building Custom Rule C:/ci/ws/src/ros2/rclpy/rclpy/CMakeLists.txt

  _rclpy_action.cpp

LINK : warning LNK4075: ignoring '/INCREMENTAL' due to '/LTCG' specification [C:\ci\ws\build\rclpy\_rclpy_action.vcxproj]

     Creating library C:/ci/ws/build/rclpy/RelWithDebInfo/_rclpy_action.lib and object C:/ci/ws/build/rclpy/RelWithDebInfo/_rclpy_action.exp

```
I think it [started](https://ci.ros2.org/job/packaging_windows/2026/msbuild/) right after #667 was merged.

---
https://github.com/osrf/buildfarmer/issues/161

**Comment by clalancette** [comment]
Huh.  In theory https://github.com/ros2/rclpy/pull/681 should have fixed that, but obviously not.  I'm not quite sure what is going on there (and why we don't see it in the nightlies).
