### ISSUE TITLE
msbuild warning in Windows debug nightlies since 2021-02-27

### ISSUE THREAD

**Issue by nuclearsandwich** [ros2/rclpy#689]
First build: https://ci.ros2.org/view/nightly/job/nightly_win_deb/1911/

It looks like these warnings were appearing previously and https://github.com/ros2/rclpy/pull/681 resolved them. However the warning returned in the 2021-02-27 nightlies. The following three PRs were merged that day and one of which may have reintroduced the warning.

* https://github.com/ros2/rclpy/pull/659
* https://github.com/ros2/rclpy/pull/675
* https://github.com/ros2/rclpy/pull/668

**Comment by clalancette** [comment]
@sloretz @cottsay Can you take a look?  Thanks.
