### ISSUE TITLE
Error management: replace asserts where appropriate

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/rclpy#83]
Right now [_rclpy.c](https://github.com/ros2/rclpy/blob/master/rclpy/src/rclpy/_rclpy.c) is full of asserts. Would be great to throw or return accordingly. This is also related to https://github.com/ros2/rclpy/issues/31

**Comment by allenh1** [comment]
@mikaelarguedas is anyone working on this?

**Comment by mikaelarguedas** [comment]
This will be part of the rclpy refactor that will be discussed next week along with #95 #31 #58 so I'd rather wait to do it in a consistent way to be sure not to conflict.

#84 is still available for grabs though

**Comment by Ridhwanluthra** [comment]
is someone working on this?
I can get this done. Please provide some more details
Thanks

**Comment by clalancette** [comment]
Since we moved away from `_rclpy.c`, I'm going to close this one out.
