### ISSUE TITLE
Error when trying to destroy publisher

### ISSUE THREAD

**Issue by CameronMatthew** [ros2/rclpy#837]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04
- Installation type:
  - binaries
- Version or commit hash:
  - galactic
- DDS implementation:
  - default (Cyclone DDS)
- Client library (if applicable):
  - rclpy

#### Steps to reproduce issue

The bug appeared in a project after migrating from foxy to galactic, so I believe the ROS 2 version used is important in reproducing this bug. I've created a minimal example node which recreates the bug (it's just a modified version of [this publisher](https://docs.ros.org/en/foxy/Tutorials/Writing-A-Simple-Py-Publisher-And-Subscriber.html))

See the code below:
``` python
import rclpy
from rclpy.node import Node
from std_msgs.msg import String


class DynamicPublisher(Node):

    def __init__(self):
        super().__init__("dynamic_publisher")
        self.publisher_ = self.create_publisher(String, "test_topic", 10)
        timer_period = 0.5
        self.timer = self.create_timer(timer_period, self.timer_callback)
        self.i = 0

    def timer_callback(self):
        msg = String()
        msg.data = "Publishing message {}".format(self.i)
        self.publisher_.publish(msg)
        self.get_logger().info("Publishing message")
        self.i += 1

        if self.i == 5:
            self.publisher_.destroy()
            #self.destroy_publisher(self.publisher_)


def main(args=None):
    rclpy.init(args=args)

    dynamic_publisher = DynamicPublisher()

    rclpy.spin(dynamic_publisher)

    dynamic_publisher.destroy_node()
    rclpy.shutdown()

if __name__ == '__main__':
    main()
```

#### Expected behavior

Publisher destroys itself cleanly after 5 messages are published

#### Actual behavior

InvalidHandle error raised. Details of the error depend on whether you destroy the publisher by running ```self.publisher_.destroy()``` or ```self.destroy_publisher(self.publisher_)```

For the former destruction method it returns:

```
rclpy._rclpy_pybind11.InvalidHandle: cannot use Destroyable because destruction was requested
```

And for the latter:

```
rclpy._rclpy_pybind11.InvalidHandle: Tried to use a handle that has been destroyed.
```

#### Additional information

This behavior is identical to [this issue](https://github.com/ros2/rclpy/issues/762) which looks like it may have been closed too early. A little stumped by this so all help is appreciated!

Thanks in advance!
----

**Comment by CameronMatthew** [comment]
Thanks a lot! Will give this a go

**Comment by fujitatomoya** [comment]
@Barry-Xu-2018 is this an actual issue for rclpy? (i do not see in that way) could we close this?

**Comment by Barry-Xu-2018** [comment]
@fujitatomoya 
 
> is this an actual issue for rclpy? (i do not see in that way) could we close this?
I think it isn't an issue. It is relevant to how to use interface.

@CameronMatthew  after confirming your code, please close this ticket.
