### ISSUE TITLE
raise NotInitializedException when rclpy.init() is not called first

### ISSUE THREAD

**Issue by wjwwood** [ros2/rclpy#84]
This is a regression of https://github.com/ros2/rclpy/pull/82, see this for more details:

https://github.com/ros2/rclpy/pull/82#issuecomment-302818268

**Comment by allenh1** [comment]
Is this something that could be worked on in the near future?

**Comment by mikaelarguedas** [comment]
:+1: yep that should be a fairly small change that can be addressed in the near future
