### ISSUE TITLE
Foxy wait_for_server() not correctly working on slow machines with ros2control/spawner

### ISSUE THREAD

**Issue by BenjaminHug8** [ros2/rclpy#842]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04
- Installation type:
  - binairies
- Version or commit hash:
  - Foxy
- Client library (if applicable):
  - rclpy,

#### Expected behavior

I use a node (a JointTrajectoryController) derived from `rclpy.node` that need to sent information to a 2nd node derived from `ros2control/spawner` .
It is critical that the 2nd node is running before sending the information.

#### Actual behavior

The 1st node use `wait_for_server()` from `ActionClient` to wait for the 2nd node to be ready before sending the information.
It works correctly on my computer but when launched with CI Github I can see the 2nd node receive the information before being full initialized.

Thus I suppose that with the CI running slowly, the 2nd get created, then `wait_for_server()` find the 2nd node "activated" and finally the 2nd node finished to be fully initialized.

Would it be something that can happen due to your code ?
Or would it be on the spawner side where the node should not show itself as activated to your function `rclpy_action_server_is_available` as it is still not completely activated ?

(Do not hesitate if I can give you more information !)

EDIT:
I open an issue on [ros_controller](https://github.com/ros-controls/ros2_controllers/issues/265) side to know if that might come from the `JointTrajectoryController`.

**Comment by BenjaminHug8** [comment]
After some search, it appears that `wait_for_server()` will call `rcl_action_server_is_available()`, that will perform several checks to know on the action server.

On those [lines](https://github.com/ros2/rcl/blob/414fdbd479b83f2b8af8235ad1fa3aeba2b0027f/rcl_action/src/rcl_action/action_client.c#L301-L312), two checks are done with `rcl_subscription_get_publisher_count` (which will check the publisher of the ros actions if I am right).

I am not sure why it is not `rcl_publisher_get_subscription_count` instead?

Maybe that would be only pertinent in my case where I need the subscriber of the ros action to be ready.
Or is there any other function such as `wait_for_server()` that will target the subscriber instead of the publisher ?

**Comment by BenjaminHug8** [comment]
Anyone has an idea about my issue or should I give more / other information?

**Comment by fujitatomoya** [comment]
> I am not sure why it is not rcl_publisher_get_subscription_count instead?

`rcl_subscription_get_publisher_count` needs to be called from the action client, cz in this case action client is subscription on topic named `feedback` and `status`. So it checks if the publisher (action server) is ready on the topic or not.

**Comment by BenjaminHug8** [comment]
> `rcl_subscription_get_publisher_count` needs to be called from the action client, cz in this case action client is subscription on topic named `feedback` and `status`. So it checks if the publisher (action server) is ready on the topic or not.

Ok thank you for the clarification!

**Comment by BenjaminHug8** [comment]
The issue has been solved on our side by waiting a `JointTrajectoryControllerState` message on the `/state` topic, confirming that the `JointTrajectoryController` is ready to receive goals.
