### ISSUE TITLE
pybind11 error during subscription take_message() when message has NaN value

### ISSUE THREAD

**Issue by jacobperron** [ros2/rclpy#848]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04
- Installation type:
  - binaries or from source
- Version or commit hash:
  - 77949d2c54b8104e48a94d0ea83c7049e18a8809
- DDS implementation:
  - I've tried rmw_fastrtps_cpp and rmw_cyclonedds
- Client library (if applicable):
  - rclpy

#### Steps to reproduce issue

1. Clone [nan_publisher](https://github.com/jacobperron/nan_publisher) to a workspace and build it.
2. Source the workspace and run the publisher. It will publish nan values to a topic `/nan`:

        ros2 run nan_publisher nan_publisher
3. Try to echo the `/nan` topic (e.g. with `ros2topic`):

        ros2 topic echo /nan

#### Expected behavior

The subscriber does not crash.

#### Actual behavior

The subscriber crashes with the following message:

```
make_tuple(): unable to convert argument of type 'object' to Python object
```
#### Additional information

The following line is failing, because (I think) `pytaken_msg` is not initialized:

https://github.com/ros2/rclpy/blob/77949d2c54b8104e48a94d0ea83c7049e18a8809/rclpy/src/rclpy/subscription.cpp#L130-L133

I've added some print statements to that file and can confirm that `pytaken_msg` evaluates to false, e.g.

```diff
+  if (!pytaken_msg) {
+    std::cerr << "We see this print statement" << std::endl;
+  }
+
   return py::make_tuple(
```

I don't know _why_ `pytaken_msg` evaluates to false, but I suppose it has to do with the message failing to be converted into Python.

**Comment by jacobperron** [comment]
The sibling test [`test_point_cloud_node.py`](https://github.com/ros-perception/image_pipeline/blob/rolling/stereo_image_proc/test/test_point_cloud_node.py) is very similar to the failing test, but does not have the same issue. So I suspect it has something to do with the message type.

**Comment by jacobperron** [comment]
It seems like there's something going awry in the stereo image processing. If I comment out [this line](https://github.com/ros-perception/image_pipeline/blob/3da80a133ea78d4273bfc35fac5a95ea5144d74f/stereo_image_proc/src/stereo_image_proc/disparity_node.cpp#L343), then the code no longer crashes.

Still, it seems wrong that rclpy would fail like this. I think the error message could probably be improved in the case that the conversion happening here fails: https://github.com/ros2/rclpy/blob/77949d2c54b8104e48a94d0ea83c7049e18a8809/rclpy/src/rclpy/subscription.cpp#L127

**Comment by jacobperron** [comment]
A division by zero is happening here, 

https://github.com/ros-perception/vision_opencv/blob/7bbc5ecc232e8faf36b45efaa2b6bc979b04157f/image_geometry/include/image_geometry/stereo_camera_model.h#L135

causing a `-nan` getting set in the ROS message here:

https://github.com/ros-perception/image_pipeline/blob/3da80a133ea78d4273bfc35fac5a95ea5144d74f/stereo_image_proc/src/stereo_image_proc/stereo_processor.cpp#L133

which then causes the executor to crash on the subscriber end when taking the message (I don't know why).

---

I can fix my immediate issue by making sure I populate CameraInfo message correctly in my test fixture. However, I think there's a separate issue here when I publish a message with a `nan` value, the subscriber crashes. I've updated the description with a reproducible example.

**Comment by clalancette** [comment]
> [ros2/rosidl_python#167](https://github.com/ros2/rosidl_python/pull/167) can fix this problem.

Yes, good call.  I'm actually going to close this one as a duplicate, since it is already fixed in Rolling and there is now a backport PR to humble for it.
