### ISSUE TITLE
MultiThreadedExecutor race condition in client.call_async

### ISSUE THREAD

**Issue by augustelalande** [ros2/rclpy#870]
This is related to #564, but the race condition goes deeper than what was stated there.

Essentially, this line:
https://github.com/ros2/rclpy/blob/379ce0a2196dd1418db4a2a98c1a9b792d99d5c9/rclpy/rclpy/executors.py#L354
can execute before this line:
https://github.com/ros2/rclpy/blob/379ce0a2196dd1418db4a2a98c1a9b792d99d5c9/rclpy/rclpy/client.py#L135

The executor then ignores the request as 'cancelled'
https://github.com/ros2/rclpy/blob/379ce0a2196dd1418db4a2a98c1a9b792d99d5c9/rclpy/rclpy/executors.py#L355-L357
and the client is stuck waiting for the future to finish.

**Comment by augustelalande** [comment]
Potentially, the solution would be to execute call_async with a lock and then require the same lock when fetching the pending_request.

**Comment by jacobperron** [comment]
Resolved in #871 

I've also created a ticket for a similar race in the action client: https://github.com/ros2/rclpy/issues/878
