### ISSUE TITLE
rclpy.duration.Duration.to_msg() loses precision

### ISSUE THREAD

**Issue by suurjaak** [ros2/rclpy#875]
## Bug report

- Operating System:
  - Ubuntu 20.04
- Installation type:
  - binaries
- Version or commit hash:
  - ros-foxy-desktop 0.9.2-1focal.20211119.123452
- Client library (if applicable):
  - rclpy

#### Steps to reproduce issue
```python
from rclpy.duration import Duration
d = Duration(nanoseconds=1234567890987654321)
m = d.to_msg()
print((d.nanoseconds % 10**9, m.nanosec))
```

#### Expected behavior
Prints `(987654321, 987654321)`.

#### Actual behavior
Prints `(987654321, 987654400)`.

**Comment by iuhilnehc-ynos** [comment]
Could you provide a PR? @suurjaak
