### ISSUE TITLE
Better typings

### ISSUE THREAD

**Issue by mateusz-lichota** [ros2/rclpy#976]
Currently using rclpy in intended ways causes typing errors due to partially unknown types of multiple methods. Even the simplest functionality (creating a publisher or a subscription) does not typecheck (tested using pylance). I've written much better typing stubs for myself, including making rclpy Subscription and Publisher generic over the mesage type, and Future generic over the return type. Would it be a welcome change to this repo to add those improved typings? Those are not evaluated at runtime, so they can't break existing code, but it would greatly improve the experience for anyone using static type checking

**Comment by apockill** [comment]
I would personally quite appreciate Subscription/Publisher/Future generics!

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/python-type-checking-in-ros2/28507/1

**Comment by clalancette** [comment]
We've added lot of types in the last year or so, though it is not 100% done yet.  Given that, I'm going to close this out as "mostly done", and we can follow-up with individual PRs as needed.
